### ISSUE TITLE
项目没run起来

### ISSUE THREAD

**Issue by sxynull** [sordors/luckDraw#1]
1、npm install
2、npm run dev
3、控制台报错、页面空白
<img width="1263" alt="image" src="https://user-images.githubusercontent.com/32755822/188112726-5f3367f6-dee8-473e-bdc5-0a985a27fbe7.png">

**Comment by sordors** [comment]
> 1、npm install 2、npm run dev 3、控制台报错、页面空白 <img alt="image" width="1263" src="https://user-images.githubusercontent.com/32755822/188112726-5f3367f6-dee8-473e-bdc5-0a985a27fbe7.png">

版本已更新，后面改了一版没上传你在试试看看好了

**Comment by fayewang2014** [comment]
> > 1、npm install 2、npm run dev 3、控制台报错、页面空白 <img alt="image" width="1263" src="https://user-images.githubusercontent.com/32755822/188112726-5f3367f6-dee8-473e-bdc5-0a985a27fbe7.png">
> 
> 版本已更新，后面改了一版没上传你在试试看看好了

最新版本，还是同样的问题。

**Comment by sxynull** [comment]
> > > 1、npm install 2、npm run dev 3、控制台报错、页面空白 <img alt="image" width="1263" src="https://user-images.githubusercontent.com/32755822/188112726-5f3367f6-dee8-473e-bdc5-0a985a27fbe7.png">
> > 
> > 
> > 版本已更新，后面改了一版没上传你在试试看看好了
> 
> 最新版本，还是同样的问题。

参考一下：
https://www.cnblogs.com/ykbk/p/16615610.html
