### ISSUE TITLE
打包问题

### ISSUE THREAD

**Issue by xyz0101** [sordors/luckDraw#2]
如果想要在web上面运行，那么应该如何打包呢？直接使用npm run build:web打包出来无法使用
![image](https://user-images.githubusercontent.com/20569072/224883683-18a849c8-e8cf-4da9-b038-b087b818ab46.png)

**Comment by sordors** [comment]
> 如果想要在web上面运行，那么应该如何打包呢？直接使用npm run build:web打包出来无法使用 ![image](https://user-images.githubusercontent.com/20569072/224883683-18a849c8-e8cf-4da9-b038-b087b818ab46.png)

不支持网页模式的，就算启动成功了，里面用的数据库lowDB也会报错
